### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Riptide00** [Riptide00/riptide00.github.io#1]
- [x] Create skeleton
- [ ] Create client-side driven message board 
- [ ] Create contact form (again clientsidedriven, dumps to pastebin?)
- [ ] Use gthub API to get my current profile picture
- [ ] followining/ followers element
